"""Full parity tests: Python vs R reference values.

Requires reference JSON files generated by scripts/generate_reference_values.R.
Run via: make parity
"""
import json
import numpy as np
import pytest
from pathlib import Path

from bw import adult_weight, child_weight
from bw.energy import EnergyBuilder

REF_DIR = Path(__file__).parent / "reference_values"


def _ref_exists(name):
    return (REF_DIR / name).exists()


def load_ref(name):
    path = REF_DIR / name
    if not path.exists():
        pytest.skip(f"Reference file {name} not found. Run: make parity-ref")
    with open(path) as f:
        return json.load(f)


def _to_array(val):
    """Convert JSON value to numpy array, handling nested lists (matrix rows)."""
    if isinstance(val, list) and len(val) > 0 and isinstance(val[0], list):
        return np.array(val, dtype=float)
    return np.atleast_2d(np.array(val, dtype=float))


# ---------------------------------------------------------------------------
# Adult model parity
# ---------------------------------------------------------------------------

class TestAdultParity:
    """Python adult model matches R output at rtol=1e-6."""

    # Map Python key -> R key (where they differ)
    VAR_MAP = {
        "Body_Weight": "Body_Weight",
        "Lean_Mass": "Lean_Mass",
        "Fat_Mass": "Fat_Mass",
        "Glycogen": "Glycogen",
        "Extracellular_Fluid": "Extracellular_Fluid",
        "Adaptive_Thermogenesis": "Adaptive_Thermogenesis",
        "Energy_Intake": "Energy_Intake",
        "BMI": "Body_Mass_Index",
    }

    def _compare(self, py_result, ref, rtol=1e-6, atol=1e-8):
        for py_key, r_key in self.VAR_MAP.items():
            if r_key not in ref or py_key not in py_result:
                continue
            py_val = np.atleast_2d(np.asarray(py_result[py_key], dtype=float))
            r_val = _to_array(ref[r_key])
            # Python adult stores (nsteps, nind); R stores (nind, nsteps)
            if py_val.shape[0] > py_val.shape[1] and r_val.shape[1] > r_val.shape[0]:
                py_val = py_val.T
            np.testing.assert_allclose(
                py_val, r_val, rtol=rtol, atol=atol,
                err_msg=f"Mismatch in {py_key}"
            )

    def test_male_baseline(self):
        ref = load_ref("adult_male_baseline.json")
        result = adult_weight(76, 1.73, 36, "male")
        self._compare(result, ref)

    def test_male_ei2400(self):
        ref = load_ref("adult_male_ei2400.json")
        result = adult_weight(76, 1.73, 36, "male", EI=2400)
        self._compare(result, ref)

    def test_female_baseline(self):
        ref = load_ref("adult_female_baseline.json")
        result = adult_weight(65, 1.65, 30, "female")
        self._compare(result, ref)

    def test_male_deficit(self):
        ref = load_ref("adult_male_deficit.json")
        EIchange = np.full((365, 1), -500.0)
        NAchange = np.zeros((365, 1))
        result = adult_weight(90, 1.80, 40, "male", EIchange=EIchange, NAchange=NAchange)
        self._compare(result, ref)

    def test_multi_individual(self):
        ref = load_ref("adult_multi.json")
        result = adult_weight([76, 65], [1.73, 1.65], [36, 30],
                              ["male", "female"])
        self._compare(result, ref)


# ---------------------------------------------------------------------------
# Child model parity
# ---------------------------------------------------------------------------

class TestChildParity:
    """Python child model matches R output at rtol=1e-6."""

    VARS = ["Fat_Free_Mass", "Fat_Mass", "Body_Weight"]

    def _compare(self, py_result, ref, rtol=1e-6, atol=1e-8):
        for var in self.VARS:
            if var not in ref:
                continue
            py_val = np.atleast_2d(np.asarray(py_result[var], dtype=float))
            r_val = _to_array(ref[var])
            np.testing.assert_allclose(
                py_val, r_val, rtol=rtol, atol=atol,
                err_msg=f"Mismatch in {var}"
            )

    def test_male_365d(self):
        ref = load_ref("child_male_365d.json")
        result = child_weight(6, "male", days=365)
        self._compare(result, ref)

    def test_female_730d(self):
        ref = load_ref("child_female_730d.json")
        result = child_weight(10, "female", days=730)
        self._compare(result, ref)

    def test_male_5yr(self):
        ref = load_ref("child_male_5yr.json")
        result = child_weight(6, "male", days=1825)
        self._compare(result, ref, rtol=1e-4)  # looser for long run


# ---------------------------------------------------------------------------
# Energy interpolation parity
# ---------------------------------------------------------------------------

class TestEnergyParity:
    """Python energy interpolation matches R output at rtol=1e-10."""

    def _compare(self, method):
        ref = load_ref(f"energy_{method.lower()}.json")
        energy = np.array([[2000.0, 2200.0, 1800.0]])
        time = np.array([0.0, 5.0, 10.0])
        builder = EnergyBuilder()
        result = builder.build(energy, time, method=method)
        r_result = _to_array(ref["energy"])
        np.testing.assert_allclose(result, r_result, rtol=1e-10,
                                   err_msg=f"Mismatch in energy {method}")

    def test_linear(self):
        self._compare("linear")

    def test_exponential(self):
        self._compare("exponential")

    def test_logarithmic(self):
        self._compare("logarithmic")

    def test_stepwise_l(self):
        self._compare("stepwise_l")

    def test_stepwise_r(self):
        self._compare("stepwise_r")
